export const LAUNCHES = {
  FETCH_LAUNCHES: "FETCH_LAUNCHES",
  FETCH_UPCOMING_LAUNCHES_SUCCESS: "FETCH_UPCOMING_LAUNCHES_SUCCESS",
  FETCH_UPCOMING_LAUNCHES: "FETCH_UPCOMING_LAUNCHES",
  FETCH_LAUNCHES_SUCCESS: "FETCH_LAUNCHES_SUCCESS",
  FETCH_LAUNCHES_FAIL: "FETCH_LAUNCHES_FAIL",
  NEXT_PAGE: "NEXT_PAGE",
};
